services:
  - type: web
    name: meu-site
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python meu_site.py"
    envVars:
      - key: TZ
        value: "America/Sao_Paulo"
    plan: free
    dockerfile: |
      FROM python:3.11-slim
      RUN apt-get update && apt-get install -y tesseract-ocr
      RUN pip install -r requirements.txt
      COPY . /app
      WORKDIR /app
      CMD ["python", "meu_site.py"]
