services:
  - type: web
    name: meu-servico
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: "python meu_site.py"

